### ISSUE TITLE
Animation delay 404 page

### ISSUE THREAD

**Issue by Esutarosa** [Esutarosa/yuppi#4]
When you get to a 404 page, animation has a delay before it starts playing, it looks very suspicious

![chrome_ZLX7BskZ2q](https://github.com/Esutarosa/yuppi/assets/107695658/09ae072d-5fd5-46c4-ac3a-95706ba9a9b1)

**Comment by DenisNysheta** [comment]
Sorry, it seemed to me that if user will visit page and see 404, i add some delays.
I have fixed this moment, really it's look better without past delay,
